import { Trip } from './types/itinerary';

export const mockTrip: Trip = {
  id: 'trip-1',
  title: 'Trip to Tokyo',
  startDate: '2025-03-25',
  endDate: '2025-03-30',
  destination: 'Tokyo',
  bucket: [],
  days: [
    {
      id: 'day-1',
      dayNumber: 1,
      date: '2025-03-25',
      summary: 'Arrival day - Light activities to recover from jet lag',
      activities: [
        {
          id: 'act-1',
          title: 'Arrive at Narita Airport',
          description: 'International flight arrival',
          category: 'transit',
          location: 'Narita Airport',
          duration: 60,
          cost: 0,
          currency: 'JPY',
          notes: 'Clear customs and immigration',
          status: 'planned',
          timeOfDay: '5:00 PM',
        },
        {
          id: 'act-2',
          title: 'Take Narita Express to Tokyo',
          description: 'Direct train to Tokyo Station',
          category: 'transit',
          location: 'Narita to Tokyo',
          duration: 60,
          cost: 3070,
          currency: 'JPY',
          notes: 'Get Suica card at the station. Purchase JR Pass if eligible.',
          status: 'planned',
          timeOfDay: '6:00 PM',
        },
        {
          id: 'act-3',
          title: 'Dinner near hotel',
          description: 'Light dinner at a local restaurant',
          category: 'eat',
          location: 'Shinjuku',
          duration: 60,
          cost: 2000,
          currency: 'JPY',
          notes: 'Try a casual izakaya or ramen shop. Don\'t overdo it on the first night.',
          status: 'planned',
          timeOfDay: '8:00 PM',
        },
        {
          id: 'act-4',
          title: 'Early rest',
          description: 'Get good sleep to recover from jet lag',
          category: 'rest',
          duration: 480,
          notes: 'Aim to sleep by 10 PM to adjust to Japan time',
          status: 'planned',
          timeOfDay: '10:00 PM',
        },
      ],
    },
    {
      id: 'day-2',
      dayNumber: 2,
      date: '2025-03-26',
      summary: 'Exploring East Tokyo - Asakusa and Akihabara',
      activities: [
        {
          id: 'act-5',
          title: 'Senso-ji Temple',
          description: 'Tokyo\'s oldest and most famous temple',
          category: 'see',
          location: 'Asakusa',
          duration: 90,
          cost: 0,
          currency: 'JPY',
          notes: 'Arrive early (8-9 AM) to avoid crowds. Explore Nakamise shopping street.',
          status: 'planned',
          timeOfDay: '9:00 AM',
          isAnchor: false,
        },
        {
          id: 'act-6',
          title: 'Lunch at Asakusa',
          description: 'Try tempura or traditional Japanese lunch',
          category: 'eat',
          location: 'Asakusa',
          duration: 60,
          cost: 1500,
          currency: 'JPY',
          notes: 'Many good tempura restaurants in the area',
          status: 'planned',
          timeOfDay: '12:00 PM',
        },
        {
          id: 'act-7',
          title: 'Tokyo Skytree',
          description: 'Tallest structure in Japan with observation decks',
          category: 'see',
          location: 'Sumida',
          duration: 120,
          cost: 2100,
          currency: 'JPY',
          notes: 'Buy tickets online in advance to skip lines. Best views on clear days.',
          status: 'planned',
          timeOfDay: '2:00 PM',
          isAnchor: true,
        },
        {
          id: 'act-8',
          title: 'Akihabara Electric Town',
          description: 'Electronics and anime/manga paradise',
          category: 'do',
          location: 'Akihabara',
          duration: 120,
          cost: 0,
          currency: 'JPY',
          notes: 'Great for electronics, anime goods, and maid cafes. Can easily spend 3+ hours here.',
          status: 'planned',
          timeOfDay: '4:30 PM',
        },
        {
          id: 'act-9',
          title: 'Dinner in Akihabara',
          description: 'Try a themed restaurant or yakiniku',
          category: 'eat',
          location: 'Akihabara',
          duration: 90,
          cost: 3000,
          currency: 'JPY',
          status: 'planned',
          timeOfDay: '7:00 PM',
        },
      ],
    },
    {
      id: 'day-3',
      dayNumber: 3,
      date: '2025-03-27',
      summary: 'Shibuya, Harajuku, and Meiji Shrine',
      activities: [
        {
          id: 'act-10',
          title: 'Meiji Shrine',
          description: 'Peaceful Shinto shrine in forested grounds',
          category: 'see',
          location: 'Harajuku',
          duration: 60,
          cost: 0,
          currency: 'JPY',
          notes: 'Visit in the morning for a peaceful atmosphere',
          status: 'planned',
          timeOfDay: '9:00 AM',
        },
        {
          id: 'act-11',
          title: 'Harajuku Takeshita Street',
          description: 'Famous shopping street with trendy fashion',
          category: 'do',
          location: 'Harajuku',
          duration: 90,
          cost: 0,
          currency: 'JPY',
          notes: 'Try crepes and explore unique boutiques',
          status: 'planned',
          timeOfDay: '10:30 AM',
        },
        {
          id: 'act-12',
          title: 'Shibuya Crossing',
          description: 'World\'s busiest pedestrian crossing',
          category: 'see',
          location: 'Shibuya',
          duration: 30,
          cost: 0,
          currency: 'JPY',
          notes: 'Watch from Starbucks 2nd floor for best view',
          status: 'planned',
          timeOfDay: '2:00 PM',
        },
        {
          id: 'act-13',
          title: 'teamLab Borderless',
          description: 'Digital art museum',
          category: 'do',
          location: 'Azabudai Hills',
          duration: 120,
          cost: 3800,
          currency: 'JPY',
          notes: 'RESERVATION REQUIRED. Book 1-2 weeks in advance.',
          status: 'planned',
          timeOfDay: '4:00 PM',
          isAnchor: true,
        },
      ],
    },
  ],
};
